const sortBy = require('sort-by');

module.exports = (dato, root) => {
  root.createDataFile('src/data/sidebar.yml', 'yaml', {
    name: dato.sidebar.siteName,
    language: dato.site.locales[0],
    intro: dato.sidebar.introText,
    copyright: dato.sidebar.copyright,
    socialProfiles: dato.socialProfiles.sort(sortBy('position')).map(profile => {
      return {
        type: profile.profileType.toLowerCase().replace(/ +/, '-'),
        url: profile.url,
      };
    })
  });

  root.directory('src/works', dir => {
    dato.works.sort(sortBy('position')).forEach((work, index) => {
      dir.createPost(`${work.slug}.md`, 'yaml', {
        frontmatter: {
          title: work.title,
          coverImage: work.coverImage.url({ w: 400, fm: 'jpg' }),
          position: index,
          excerpt: work.excerpt,
        }
      });
    });
  });

//   dato.collectionItemTypes.forEach(itemType => {
//     root.directory(`content/_${itemType.apiKey}/`, dir => {
//       dato.itemsOfType(itemType).forEach(item => {
//         dir.createPost(`${item.autogeneratedSlug()}.md`, 'toml', { frontmatter: item.toMap() });
//       });
//     });
//   });
};

